### ISSUE TITLE
Tracking Issue for Alpha Release

### ISSUE THREAD

**Issue by mfdorst** [MagmaWM/MagmaWM#106]
These are all the things that must be done before we are ready for an alpha release.

* [ ] XWayland support
* [ ] Multi-monitor support
* [ ] Dynamic tiling support
* [ ] IPC
* [ ] Window floating
* [ ] Window switching
* [ ] Window resizing
* [ ] Workspaces or tags
